imports:
    - { resource: parameters.yaml }
    - { resource: phpcr.yaml }

# Twig Configuration

# Swiftmailer Configuration

# cmf configuration

knp_menu:
    twig: true

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }

lunetics_locale:
    strict_mode: true
    guessing_order:
        - router
        - cookie
        - browser
    allowed_locales: '%locales%'


