cmf_core:
    multilang:
        locales: '%locales%'
    persistence:
        phpcr:
            enabled: true

cmf_menu:
    voters:
        content_identity: ~

cmf_resource:
    description:
        enhancers: [doctrine_phpcr_position]
    repositories:
        default:
            type: doctrine/phpcr-odm

cmf_tree_browser:
    icons:
        App\Document\DemoSeoContent: 'fa fa-file-text-o'
        Sonata\BlockBundle\Model\BlockInterface: 'fa fa-cube'
        Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata: 'fa fa-search'
        Symfony\Cmf\Bundle\MenuBundle\Model\MenuNode: 'fa fa-share-square-o'
        Symfony\Cmf\Bundle\RoutingBundle\Model\Route: 'fa fa-link'
        Symfony\Cmf\Bundle\RoutingBundle\Model\RedirectRoute: 'fa fa-reply'

cmf_sonata_phpcr_admin_integration:
    bundles:
        seo: ~
        menu: ~
        core: ~
        content:
           ivory_ckeditor:
              config_name: cmf_sonata_phpcr_admin_integration
        block:
            basepath: /cms/content
            menu_basepath: /cms/content
        routing: ~
cmf_routing:
    chain:
        routers_by_id:
            router.default: 20
            cmf_routing.dynamic_router: 100
    dynamic:
        route_collection_limit: 10
        controllers_by_type:
            demo_type: app.content_controller:typeAction
        controllers_by_class:
            App\Document\DemoClassContent: app.content_controller:classAction
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent: static_content/index.html.twig

cmf_seo:
    title: 'CMF Sandbox - %%content_title%%'
    description: 'The Content Management Framework. %%content_description%%'
    alternate_locale: ~

cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
    mapping:
        resources:
            - '%kernel.project_dir%/src/Resources/config/cmf_routing_auto.yml'